name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/240644792863/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@cloud-portfolio-509107.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check || true

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
      
      - name: Install Frontend Dependencies
        working-directory: ./site
        run: npm install
      
      - name: Build Astro Site
        working-directory: ./site
        run: npm run build

      - name: Deploy to Firebase Hosting
        working-directory: ./site
        run: npx firebase-tools deploy --only hosting --project cloud-portfolio-509107

  deploy-api:
    name: Build & Deploy API
    runs-on: ubuntu-latest
    # Waits for Terraform to finish successfully
    needs: deploy-infra 
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/240644792863/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@cloud-portfolio-509107.iam.gserviceaccount.com'

      - name: Configure Docker Auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        working-directory: ./backend
        run: |
          docker build -t us-central1-docker.pkg.dev/cloud-portfolio-509107/cloud-portfolio-repo/visitor-api:latest .
          docker push us-central1-docker.pkg.dev/cloud-portfolio-509107/cloud-portfolio-repo/visitor-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy visitor-api \
            --image us-central1-docker.pkg.dev/cloud-portfolio-509107/cloud-portfolio-repo/visitor-api:latest \
            --region us-central1 \
            --max 3 \
            --concurrency 20 \
            --allow-unauthenticated \
            --project cloud-portfolio-509107